project_id = "qgpsfcrmubqhpjnpdiha"

[functions.google-oauth-callback]
verify_jwt = false

[functions.mercadopago-pix-create]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.mercadopago-checkout-create]
verify_jwt = false

[functions.mercadopago-process-payment]
verify_jwt = false

[functions.mercadopago-public-key]
verify_jwt = false
